### ISSUE TITLE
fetch xsection info easier

### ISSUE THREAD

**Issue by Ming-Yan** [cms-btv-pog/BTVNanoCommissioning#73]
Get info from GenXSAnalyzer with DAS path

Discuss with @uttiyasarkar 
https://twiki.cern.ch/twiki/bin/view/CMS/HowToGenXSecAnalyzer#Automated_scripts_to_compute_the

**Comment by demuller** [comment]
### How to transform GenXsecAnalyzer output into json format as known from XSDB

GitHub Gist with Sen's modified script: https://gist.github.com/demuller/aeae1f30785aebb02d023dc2bfa4f614 (main difference to [his version](https://github.com/Senphy/xsecdb/blob/test/scripts/xsec_calc_auto/4_prepare_json_xsec_database.py): added center-of-mass energy of 13.6 TeV)

tested under the following environment: `CMSSW_13_0_13` (most likely will work independently from CMSSW, but was set up due to previous usage of GenXsecAnalyzer)

needs `datasets.txt` as input file (i.e. list of sample paths in CMS DAS, for example `/QCD_PT-15to30_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM`) as well as GenXSecAnalyzer output (stored e.g. as `xsec/xsec_QCD_PT-15to30_TuneCP5_13p6TeV_pythia8.log`)
