### ISSUE TITLE
parsl version / submission issue

### ISSUE THREAD

**Issue by Ming-Yan** [cms-btv-pog/BTVNanoCommissioning#92]

**Comment by uttiyasarkar** [comment]
The user encounters the following error while using the latest job distributor version of  Parsl==2024.03.18:
`Job is marked as MISSING since the workers failed to register to the executor. Check the stdout/stderr logs in the submit_scripts directory for more debug information`

The installation of the parsl version can be forced to the last working version of parsl==2024.01.29 with pypi built which works fine. This is a quick fix, but we might want to debug more in future.
